variable "tenant" {}
variable "name" {}
variable "environment" {}
variable "vpc_id" {}
variable "cidr_block" {}
variable "subnet_id" {}
variable "encryption" {}
variable "kms_key_id" {}
variable "ec2_name" {}
variable "ami_id" {}
variable "instance_type" {}
variable "associate_public_ip_address" {}
variable "create_eip" {}
variable "detailed_monitoring" {}
variable "stop_protection" {}
variable "termination_protection" {}
variable "source_dest_check" {}
variable "key_name" {}
variable "user_data" {}
variable "delete_volumes_on_termination" {}
variable "root_volume_type" {}
variable "root_volume_size" {}
variable "root_throughput" {}
variable "root_iops" {}
variable "data_disks" {}
variable "ingress" {}